'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ApusVirtualPostOffice.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Letter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Letter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Package", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Parcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Parcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Postcard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Postcard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Side greater than 30cm. Postage Price is .
        '''</summary>
        Friend ReadOnly Property strLargeEnvolope() As String
            Get
                Return ResourceManager.GetString("strLargeEnvolope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longest side exceeding 1200mm will be charged an extra amount of .
        '''</summary>
        Friend ReadOnly Property strLargePackageParcel() As String
            Get
                Return ResourceManager.GetString("strLargePackageParcel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Postage Price is .
        '''</summary>
        Friend ReadOnly Property strPackageParcel() As String
            Get
                Return ResourceManager.GetString("strPackageParcel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max weight 2000 gr, longest side max 500 mm, thickness max 250 mm.                                                                                                                                                                                                                   Large envelop when longest side -&gt; 30..
        '''</summary>
        Friend ReadOnly Property strPostCard() As String
            Get
                Return ResourceManager.GetString("strPostCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Letter with predefined measurements. Postage is .
        '''</summary>
        Friend ReadOnly Property strPostCards() As String
            Get
                Return ResourceManager.GetString("strPostCards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SEK .
        '''</summary>
        Friend ReadOnly Property strSweKronor() As String
            Get
                Return ResourceManager.GetString("strSweKronor", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
